# Book Recommender System
Done by Kaushal Mishra

In [ ]:
#importing libraries
import pandas as pd
import numpy as np

In [2]:
#loading the dataset
books = pd.read_csv(r"C:\Users\mishr\OneDrive\Desktop\books dataset\books_new.csv")

In [4]:
#Exploring the Data
books.shape

(211, 6)

In [5]:
books.head()

Title            Author       Genre           SubGenre  \
0  Fundamentals of Wavelets  Goswami, Jaideva        tech  signal_processing   
1                Data Smart     Foreman, John        tech       data_science   
2  God Created the Integers  Hawking, Stephen        tech        mathematics   
3         Superfreakonomics   Dubner, Stephen     science          economics   
4               Orientalism      Said, Edward  nonfiction            history   

   Height      Publisher  
0     228          Wiley  
1     235          Wiley  
2     197        Penguin  
3     179  HarperCollins  
4     197        Penguin

In [6]:
books.describe()

Height
count  211.000000
mean   206.056872
std     26.828141
min    160.000000
25%    180.000000
50%    199.000000
75%    229.500000
max    283.000000

In [7]:
books.head(1)['Author'].values

array(['Goswami, Jaideva'], dtype=object)

In [8]:
#sorting out important columns
books = books[['Title','Author','Genre','SubGenre']]

In [9]:
books.head()

Title            Author       Genre           SubGenre
0  Fundamentals of Wavelets  Goswami, Jaideva        tech  signal_processing
1                Data Smart     Foreman, John        tech       data_science
2  God Created the Integers  Hawking, Stephen        tech        mathematics
3         Superfreakonomics   Dubner, Stephen     science          economics
4               Orientalism      Said, Edward  nonfiction            history

In [10]:
#finding and removing missing values
books.isnull().sum()

Title        0
Author      24
Genre        0
SubGenre     0
dtype: int64

In [11]:
books.dropna(inplace = True)
books.isnull().sum()

Title       0
Author      0
Genre       0
SubGenre    0
dtype: int64

In [12]:
books.shape

(187, 4)

In [13]:
#finding and removing duplicate values
books.duplicated().sum()

1

In [14]:
books.drop_duplicates(subset = 'Title', keep = 'first', inplace = True)
books.duplicated().sum()

0

In [15]:
#covnert string of list to list (not used in this program)
import ast
ast.literal_eval

<function ast.literal_eval(node_or_string)>

In [16]:
books.dtypes

Title       object
Author      object
Genre       object
SubGenre    object
dtype: object

In [17]:
books.head()

Title            Author       Genre           SubGenre
0  Fundamentals of Wavelets  Goswami, Jaideva        tech  signal_processing
1                Data Smart     Foreman, John        tech       data_science
2  God Created the Integers  Hawking, Stephen        tech        mathematics
3         Superfreakonomics   Dubner, Stephen     science          economics
4               Orientalism      Said, Edward  nonfiction            history

In [18]:
books['Genre'].unique()

array(['tech', 'science', 'nonfiction', 'fiction', 'philosophy'],
      dtype=object)

In [19]:
books['SubGenre'].unique()

array(['signal_processing', 'data_science', 'mathematics', 'economics',
       'history', 'psychology', 'classic', 'computer_science', 'novel',
       'science', 'autobiography', 'physics', 'objectivism', 'trivia',
       'misc', 'poetry', 'education', 'philosophy', 'anthology', 'legal'],
      dtype=object)

In [20]:
#making author names in firstnamelastname format
books['Author'] = books['Author'].apply(lambda x: ''.join(x.split(',')[::-1]).strip().replace(',','').lower())
books['Author']

0        jaidevagoswami
1           johnforeman
2        stephenhawking
3         stephendubner
4            edwardsaid
             ...       
206          terencetao
207         steveeddins
208        georgeorwell
209    fyodordostoevsky
210      charlesdickens
Name: Author, Length: 186, dtype: object

In [21]:
# removing _ from SubGenre column
books['SubGenre'] = books['SubGenre'].apply(lambda x:x.replace('_',''))
books['SubGenre']

0      signalprocessing
1           datascience
2           mathematics
3             economics
4               history
             ...       
206         mathematics
207    signalprocessing
208             classic
209             classic
210             classic
Name: SubGenre, Length: 186, dtype: object

In [22]:
 books.head()

Title          Author       Genre          SubGenre
0  Fundamentals of Wavelets  jaidevagoswami        tech  signalprocessing
1                Data Smart     johnforeman        tech       datascience
2  God Created the Integers  stephenhawking        tech       mathematics
3         Superfreakonomics   stephendubner     science         economics
4               Orientalism      edwardsaid  nonfiction           history

In [23]:
#checking how many times the values are repeated in the columns, just for analysis

repeated_values = {}

# loop through each column in the dataframe
for col in books.columns:
    # check if the column has any repeated values
    if books.duplicated(subset=[col]).any():
        # find the counts of each value in the column
        value_counts = books[col].value_counts()
        # filter the value counts to only include the repeated values
        repeated_counts = value_counts[value_counts > 1]
        # store the repeated counts in the dictionary
        repeated_values[col] = repeated_counts.to_dict()

# print the result
if len(repeated_values) > 0:
    for col, counts in repeated_values.items():
        print(f"The column {col} has the following repeated values:")
        for value, count in counts.items():
            print(f" - {value}: {count} times")
else:
    print("There are no repeated values in any column")

The column Author has the following repeated values:
 - johnsteinbeck: 8 times
 - p ldeshpande: 7 times
 - alexrutherford: 5 times
 - aynrand: 4 times
 - william smaugham: 4 times
 - amartyasen: 4 times
 - steiglarsson: 3 times
 - dominiquelapierre: 3 times
 - shashitharoor: 3 times
 - bertrandrussell: 3 times
 - williamdalrymple: 3 times
 - fritjofcapra: 3 times
 - deshpande p l: 3 times
 - frederickforsyth: 3 times
 - jefferyarcher: 2 times
 - robertfisk: 2 times
 - arthur conandoyle: 2 times
 - yashwantkanetkar: 2 times
 - simonsingh: 2 times
 - terencetao: 2 times
 - peterdrucker: 2 times
 - georgeorwell: 2 times
 - bobwoodward: 2 times
 - stephenhawking: 2 times
 - stephendubner: 2 times
 - vladimirvapnik: 2 times
 - richardgordon: 2 times
 - fyodordostoevsky: 2 times
 - palkhivala: 2 times
The column Genre has the following repeated values:
 - fiction: 59 times
 - nonfiction: 56 times
 - tech: 36 times
 - science: 21 times
 - philosophy: 14 times
The column SubGenre has the follo

In [50]:
#making a new column 'Tags'
books['Tags'] = books['Author'] + ',' + books['Genre'] + ',' + books['SubGenre']
books.head()

Title          Author       Genre          SubGenre  \
0  Fundamentals of Wavelets  jaidevagoswami        tech  signalprocessing   
1                Data Smart     johnforeman        tech       datascience   
2  God Created the Integers  stephenhawking        tech       mathematics   
3         Superfreakonomics   stephendubner     science         economics   
4               Orientalism      edwardsaid  nonfiction           history   

                                   Tags  
0  jaidevagoswami,tech,signalprocessing  
1          johnforeman,tech,datascience  
2       stephenhawking,tech,mathematics  
3       stephendubner,science,economics  
4         edwardsaid,nonfiction,history

In [51]:
#new dataset which only has title and tags columns
new_df = books[['Title','Tags']]
new_df.head()

Title                                  Tags
0  Fundamentals of Wavelets  jaidevagoswami,tech,signalprocessing
1                Data Smart          johnforeman,tech,datascience
2  God Created the Integers       stephenhawking,tech,mathematics
3         Superfreakonomics       stephendubner,science,economics
4               Orientalism         edwardsaid,nonfiction,history

In [64]:
#Now building ML model from sklearn
#Vectoring the tags
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer (max_features = 200)

In [53]:
vectors = cv.fit_transform(new_df['Tags']).toarray()

In [54]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [55]:
vectors[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0], dtype=int64)

In [58]:
cv.get_feature_names_out()

array(['abrahameraly', 'adamsmith', 'adolfhitler', 'albertcamus',
       'aldoushuxley', 'alexrutherford', 'alfredstonier', 'allendowney',
       'allenpoe', 'amartyasen', 'amiraczel', 'amitavghosh',
       'andrewtanenbaum', 'andyoram', 'anthology', 'arthur',
       'autobiography', 'aynrand', 'bbc', 'bertrandrussell', 'bobdylan',
       'bobwoodward', 'braithwaite', 'carlsagan', 'cedricvillani',
       'charlesdickens', 'classic', 'computerscience', 'conandoyle',
       'danbrown', 'datascience', 'davidbodanis', 'davidforsyth',
       'deshpande', 'dominiquelapierre', 'drewconway', 'earle',
       'economics', 'edgar', 'education', 'edwardsaid', 'ericraymond',
       'ernesthemingway', 'fiction', 'frankkafka', 'frankshih',
       'frederickforsyth', 'fritjofcapra', 'fyodordostoevsky',
       'garybradsky', 'georgeorwell', 'geralddurrell', 'geraldsussman',
       'greene', 'gutierrez', 'gwells', 'hartduda', 'history',
       'hussainzaidi', 'jaidevagoswami', 'jamesgleick', 'jawaharlal

In [60]:
len(cv.get_feature_names_out())

158

In [66]:
#finding cosine similarity between vectors
from sklearn.metrics.pairwise import cosine_similarity

In [72]:
similarity = cosine_similarity(vectors)

In [73]:
cosine_similarity(vectors).shape

(186, 186)

In [74]:
similarity

array([[1.        , 0.33333333, 0.33333333, ..., 0.        , 0.        ,
        0.        ],
       [0.33333333, 1.        , 0.33333333, ..., 0.        , 0.        ,
        0.        ],
       [0.33333333, 0.33333333, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.66666667,
        0.66666667],
       [0.        , 0.        , 0.        , ..., 0.66666667, 1.        ,
        0.66666667],
       [0.        , 0.        , 0.        , ..., 0.66666667, 0.66666667,
        1.        ]])

In [77]:
similarity[0]

array([1.        , 0.33333333, 0.33333333, 0.        , 0.        ,
       0.33333333, 0.        , 0.        , 0.66666667, 0.        ,
       0.28867513, 0.        , 0.        , 0.33333333, 0.        ,
       0.        , 0.33333333, 0.33333333, 0.        , 0.        ,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.33333333, 0.33333333, 0.33333333, 0.66666667, 0.33333333,
       0.66666667, 0.66666667, 0.33333333, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [98]:
#code forfinding index of similar books
sorted(list(enumerate(similarity[0])),reverse=True,key= lambda x:x[1])[1:6]

[(8, 0.6666666666666669),
 (58, 0.6666666666666669),
 (60, 0.6666666666666669),
 (61, 0.6666666666666669),
 (135, 0.6666666666666669)]

In [111]:
#recommender function
def recommend(book):
    book_index = new_df[new_df['Title'] == book].index[0]
    distances = similarity[book_index]
    books_list = sorted(list(enumerate(distances)),reverse=True,key= lambda x:x[1])[1:6]
    
    for i in books_list:
        print(new_df.iloc[i[0]].Title)
        
  

In [113]:
recommend('Data Smart')

Nature of Statistical Learning Theory, The
Statistical Decision Theory'
Data Mining Handbook
Machine Learning for Hackers
Signal and the Noise, The


In [110]:
new_df.iloc[8].Title

'Image Processing & Mathematical Morphology'